<!--<h1>ARTIGOS</h1>
<table border="1px">
?php //echo print_r($this->view->artigos)?>
?php foreach($this->view->artigos as $artigo): ?>
    <tr>
        <td>?=$artigo['id']?></td>
        <td>?=$artigo['titulo']?></td>
        <td style="width: 350px">?=$artigo['conteudo']?></td>
    </tr>
?php endforeach ?>
</table>
-->
<div class="col-lg-9 white" >
    <div class="page-header">
        <h1>Page Index <small>Subtext for header page index</small></h1>
    </div>
</div>